apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: oasisforsaken/eventseat-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              # แก้ไข: ตัด replicaSet ออกเพื่อให้ต่อกับ Single Mongo ได้
              value: mongodb://mongo:27017/event_service
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: '100m' # ปรับลดเพื่อให้รันบน VPS ได้ง่ายขึ้น
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            httpGet:
              path: /api
              port: 3001
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /api
              port: 3001
            initialDelaySeconds: 20
      restartPolicy: Always
