apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3001 # Port ใน Cluster
      targetPort: 3001 # Port ของ Pod
      nodePort: 30002 # Port จาก Node (ใช้กับ Ingress)
