apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    # เปลี่ยนเป็น true เพื่อให้ระบบปลอดภัยและบังคับใช้ HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: nginx
  # --- เพิ่มส่วนนี้เข้าไป ---
  tls:
    - hosts:
        - api.event-seat.elitefund.fun
      secretName: event-seat-tls # <--- ต้องระบุชื่อ Secret ที่เก็บใบเซอร์
  # -----------------------
  rules:
    - host: api.event-seat.elitefund.fun
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 3001
