apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo # อย่าลืม sudo mkdir -p /mnt/data/mongo ที่ VPS
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          volumeMounts:
            - name: mongo-data # <--- จุดที่ 1: ต้องชื่อนี้
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-data # <--- จุดที่ 2: ต้องเปลี่ยนจาก mongo-name เป็น mongo-data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: manual
        resources:
          requests:
            storage: 5Gi
